### ISSUE TITLE
富文本消息拿到的contentType是0

### ISSUE THREAD

**Issue by erlangzhang** [WuKongIM/WuKongIMiOSSDK#1]
富文本消息拿到的contentType是0, 在没有注册WKMessageContent之前拉取到的消息落库的contentType为0，再升级支持也不会将消息转回支持的contentType了

**Comment by erlangzhang** [comment]
这个会导致新版本支持了老消息，也无法查看未知消息了

**Comment by tangtaoit** [comment]
已修复
