### ISSUE TITLE
获取历史消息一直是0条

### ISSUE THREAD

**Issue by xiaowei772028339** [WuKongIM/WuKongIMiOSSDK#8]
我和demo一样 初始化的时候调用了， setSyncChannelMessageProvider 方法。只改了里面网络请求方法，也拿到了数据，最后callback(model,nil);同步过去

但是调用这个方法时候
[WKSDK.shared.chatManager pullLastMessages:self.channel limit:15  complete:^(NSArray<WKMessage *> * _Nonnull messages, NSError * _Nonnull error) {

messages一直返回空数组，
拿不到数据 是什么原因呢？是我的数据结构不对造成的吗

**Comment by tangtaoit** [comment]
看下你对接的接口有没有返回数据，和callback(model,nil);的时候model是否有recent数据

**Comment by xiaowei772028339** [comment]
> 看下你对接的接口有没有返回数据，和callback(model,nil);的时候model是否有recent数据
> 
> pullLastMessages的数据来自你的接口

您好，这是图片

<img width="482" alt="WechatIMG1301" src="https://github.com/user-attachments/assets/9d4c6cb8-7f70-494a-b595-bafb3dd980e5">
是有数据，结构是一样的，就payload 服务端做了base64处理，传model前，我已经andemo做了转换

控制的会偶尔提示
getOrSyncHistoryMessages最大重试次数结束！

**Comment by tangtaoit** [comment]
type=99是命令消息  pullLastMessages肯定获取不到 pullLastMessages是获取聊天消息，非命令消息, 如果你想自定义消息 参考文档：https://githubim.com/sdk/iossdk/advance/custommessage.html

**Comment by tangtaoit** [comment]
如果例子程序pullLastMessages可以返回，那你只能自己对比下例子程序的代码了，我们没你的代码 也不好分析

**Comment by xiaowei772028339** [comment]
好的 感谢
